[workspace]
members = ["silk*"]
resolver = "2"

[workspace.dependencies]
bevy = "0.11"
matchbox_signaling = { git = "https://github.com/johanhelsing/matchbox", rev = "f99d246" }
bevy_matchbox = { git = "https://github.com/johanhelsing/matchbox", rev = "f99d246" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
serde_json = "1.0"
