[workspace]
members = ["silk-server", "silk-client", "silk-common"]
resolver = "2"

[workspace.dependencies]
bevy = "0.10"
matchbox_signaling = { git = "https://github.com/johanhelsing/matchbox", rev = "06c7e55" }
bevy_matchbox = { git = "https://github.com/johanhelsing/matchbox", rev = "06c7e55" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
serde_json = "1.0"
