[workspace]
members = ["bevy-silk", "crates/*", "demo/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.8.0"
license = "MIT/Apache-2.0"

[workspace.dependencies]
bevy = { version = "0.12", default-features = false }
bevy_matchbox = { git = "ssh://git@github.com/vectorgameexperts/matchbox.git", rev = "a618737" }
