[workspace]
members = ["bevy-silk", "crates/*", "demo/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.8.4"
license = "MIT/Apache-2.0"

[workspace.dependencies]
bevy = { version = "0.12", default-features = false }
# TODO: Replace with 0.8.1 after https://github.com/johanhelsing/matchbox/issues/392
bevy_matchbox = { git = "https://github.com/johanhelsing/matchbox", rev = "fa5c765" }
