[workspace]
members = ["crates/*", "demo/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.7.2"
license = "MIT/Apache-2.0"

[workspace.dependencies]
bevy = { version = "0.11", default-features = false }
# Switch back to matchbox 0.7 after https://github.com/johanhelsing/matchbox/pull/283
matchbox_signaling = { git = "ssh://git@github.com/vectorgameexperts/matchbox.git", rev = "c77c57e" }
bevy_matchbox = { git = "ssh://git@github.com/vectorgameexperts/matchbox.git", rev = "c77c57e" }
tokio = { version = "1", default-features = false }
async-compat = "0.2"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
serde_json = "1.0"

[package]
name = "silk"
description = "Bevy networking tools built on matchbox."
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
silk-server = { optional = true, path = "crates/silk-server" }
silk-client = { optional = true, path = "crates/silk-client" }
silk-net = { path = "crates/silk-net", default-features = false }
silk-common = { path = "crates/silk-common" }

[features]
default = []
client = ["dep:silk-client"]
server = ["dep:silk-server"]
binary = ["silk-net/binary"]
