[workspace]
members = [
    "silk-signaller",
    "silk-server",
    "silk-client",
    "silk-common"
]

[workspace.dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
serde_json = "1.0"