[workspace]
members = ["crates/*", "demo/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.7.1"
license = "MIT/Apache-2.0"

[workspace.dependencies]
bevy = { version = "0.11", default-features = false }
matchbox_signaling = { git = "https://github.com/johanhelsing/matchbox", version = "0.7" }
bevy_matchbox = { git = "https://github.com/johanhelsing/matchbox", version = "0.7" }
tokio = { version = "1", default-features = false }
async-compat = "*"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
serde_json = "1.0"

[package]
name = "silk"
description = "Bevy networking tools built on matchbox."
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
silk-server = { optional = true, path = "crates/silk-server" }
silk-client = { optional = true, path = "crates/silk-client" }
silk-net = { path = "crates/silk-net", default-features = false }
silk-common = { path = "crates/silk-common" }

[features]
default = []
client = ["dep:silk-client"]
server = ["dep:silk-server"]
binary = ["silk-net/binary"]
