[workspace]
members = [
    "silk-signaller",
    "silk-server",
    "silk-client",
    "silk-common",
]
resolver="2"

[workspace.dependencies]
bevy = "0.9"
matchbox_socket = { git = "https://github.com/johanhelsing/matchbox", rev = "420b34d" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
serde_json = "1.0"