[workspace]
members = ["bevy-rtc", "bevy-rtc-macros", "demos/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.8.9"
license = "MIT/Apache-2.0"
description = "A client-server library designed over WebRTC for Bevy"
repository = "https://github.com/vectorgameexperts/bevy-rtc"
authors = ["Spencer C. Imbleau"]
keywords = ["gamedev"]

[workspace.dependencies]
bevy = { version = "0.12", default-features = false }
bevy_matchbox = "0.8"
