[workspace]
members = ["bevy-silk", "crates/*", "demos/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.8.8"
license = "MIT/Apache-2.0"

[workspace.dependencies]
bevy = { version = "0.12", default-features = false }
bevy_matchbox = "0.8"
