[package]
name = "bevy-silk"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "game"
path = "src/main.rs"

[dependencies]
bevy = "0.9"
matchbox_socket = { workspace = true }
silk-common = { path = "../silk-common" }