[package]
name = "ping-server"
version.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
bevy = { workspace = true }
bevy_rtc = { path = "../../bevy_rtc", features = ["server"] }
protocol = { path = "../protocol" }
