[package]
name = "silk-client"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true }
silk-common = { path = "../silk-common" }
silk-net = { path = "../silk-net" }
