[package]
name = "silk-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
matchbox_socket = { git = "https://github.com/johanhelsing/matchbox", rev = "c9d10cbab8b29eafa81422ec4784e1ea84b10dac" }
silk-common = { path = "../silk-common" }
anyhow = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }